# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0004_question_m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='m',
        ),
    ]
