# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0005_remove_question_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(),
        ),
    ]
